services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rbac
    ports:
      - "5433:5432"
    volumes:
      - postgres_rbac_data:/var/lib/postgresql/data

  rbac-service:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: rbac
      DB_PORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - postgres

volumes:
  postgres_rbac_data: