name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for Postgres to be ready
        run: sleep 30

      - name: Run tests
        run: docker-compose exec order-service go test ./... -v

      - name: Shut down containers
        if: always()
        run: docker-compose down
